// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDL3Q568ap6Q6TG4Bw25CfWaWGseMQyRJ8',
    appId: '1:818847309984:web:180984c9ba608ed1f3e9c5',
    messagingSenderId: '818847309984',
    projectId: 'kitchencatalogue',
    authDomain: 'kitchencatalogue.firebaseapp.com',
    storageBucket: 'kitchencatalogue.firebasestorage.app',
    measurementId: 'G-3PZ5NVNEYW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7bwXp8u42HIAXbE1DEu6qLwYFK1HFR4k',
    appId: '1:818847309984:android:1139773daf829d99f3e9c5',
    messagingSenderId: '818847309984',
    projectId: 'kitchencatalogue',
    storageBucket: 'kitchencatalogue.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArJZNM53gVy0ZaemiYyrlBAepeWMhE2Us',
    appId: '1:818847309984:ios:587c478bb1cf4f34f3e9c5',
    messagingSenderId: '818847309984',
    projectId: 'kitchencatalogue',
    storageBucket: 'kitchencatalogue.firebasestorage.app',
    iosBundleId: 'com.example.helloFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArJZNM53gVy0ZaemiYyrlBAepeWMhE2Us',
    appId: '1:818847309984:ios:587c478bb1cf4f34f3e9c5',
    messagingSenderId: '818847309984',
    projectId: 'kitchencatalogue',
    storageBucket: 'kitchencatalogue.firebasestorage.app',
    iosBundleId: 'com.example.helloFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDL3Q568ap6Q6TG4Bw25CfWaWGseMQyRJ8',
    appId: '1:818847309984:web:e87283b8e529c073f3e9c5',
    messagingSenderId: '818847309984',
    projectId: 'kitchencatalogue',
    authDomain: 'kitchencatalogue.firebaseapp.com',
    storageBucket: 'kitchencatalogue.firebasestorage.app',
    measurementId: 'G-G5QZDN6007',
  );
}
